"use client";

import { Pagination } from "@/components/pagination";
import { Item } from "./item";
import { useState } from "react";
const randonTexts = [
    "The rapid advancement of artificial intelligence has revolutionized numerous industries, from healthcare to finance. Machine learning algorithms now process vast amounts of data to identify patterns and make predictions with unprecedented accuracy. This technological evolution has led to improved diagnostic capabilities in medicine, more efficient financial trading systems, and enhanced customer service through intelligent chatbots. However, the integration of AI also raises important ethical considerations regarding privacy, bias in decision-making, and the future of human employment. As we continue to develop these technologies, it's crucial to establish robust frameworks for responsible AI development and implementation.",
    "Climate change presents one of the most significant challenges facing our global community today. Rising temperatures, extreme weather events, and shifting precipitation patterns are affecting ecosystems and human societies worldwide. Scientists have observed accelerated glacial melting, rising sea levels, and increasing frequency of natural disasters. These changes impact agriculture, water resources, and biodiversity, threatening food security and economic stability. International cooperation and immediate action are essential to reduce greenhouse gas emissions, develop sustainable energy solutions, and implement effective adaptation strategies to protect vulnerable communities and preserve our planet for future generations.",
    "The evolution of space exploration has entered an exciting new era with private companies joining government agencies in the race to the stars. Recent technological breakthroughs have made space travel more accessible and economically viable than ever before. Reusable rocket technology, advanced satellite systems, and plans for lunar bases and Mars colonization are reshaping our understanding of what's possible. This commercial space age promises new opportunities for scientific research, resource exploitation, and even space tourism. However, it also raises important questions about space debris management, resource rights, and international cooperation in the final frontier.",
    "The human brain remains one of the most complex and fascinating organs in existence, with neuroscientists continuously uncovering new insights into its functioning. Recent research has revealed remarkable findings about neuroplasticity, memory formation, and consciousness. Studies show how our brains constantly rewire themselves in response to new experiences and learning, maintaining this adaptability throughout our lives. Understanding these mechanisms has led to breakthrough treatments for neurological conditions and innovative approaches to education and cognitive enhancement. The intersection of neuroscience with artificial intelligence is opening new frontiers in brain-computer interfaces and cognitive augmentation.",
    "The global food system is undergoing a dramatic transformation as we face the challenges of feeding a growing population while maintaining environmental sustainability. Innovative agricultural technologies, including vertical farming, precision agriculture, and lab-grown meat, are revolutionizing food production. These advances promise to reduce water usage, minimize land requirements, and decrease greenhouse gas emissions. Additionally, the rise of plant-based alternatives and cellular agriculture is reshaping consumer preferences and industry practices. However, ensuring equitable access to nutritious food while supporting small-scale farmers remains a critical challenge in this agricultural revolution.",
    "The digital revolution has fundamentally altered how we communicate, work, and interact with the world around us. Social media platforms have created global communities while simultaneously raising concerns about privacy, mental health, and the spread of misinformation. The rise of remote work, accelerated by recent global events, has transformed traditional office culture and labor markets. Blockchain technology and cryptocurrencies are challenging conventional financial systems, while the Internet of Things is creating increasingly connected and smart environments. As we navigate this digital transformation, questions of digital rights, cybersecurity, and technological inequality become increasingly important.",
    "The rapid advancement of artificial intelligence has revolutionized numerous industries, from healthcare to finance. Machine learning algorithms now process vast amounts of data to identify patterns and make predictions with unprecedented accuracy. This technological evolution has led to improved diagnostic capabilities in medicine, more efficient financial trading systems, and enhanced customer service through intelligent chatbots. However, the integration of AI also raises important ethical considerations regarding privacy, bias in decision-making, and the future of human employment. As we continue to develop these technologies, it's crucial to establish robust frameworks for responsible AI development and implementation.",
    "Climate change presents one of the most significant challenges facing our global community today. Rising temperatures, extreme weather events, and shifting precipitation patterns are affecting ecosystems and human societies worldwide. Scientists have observed accelerated glacial melting, rising sea levels, and increasing frequency of natural disasters. These changes impact agriculture, water resources, and biodiversity, threatening food security and economic stability. International cooperation and immediate action are essential to reduce greenhouse gas emissions, develop sustainable energy solutions, and implement effective adaptation strategies to protect vulnerable communities and preserve our planet for future generations.",
    "The evolution of space exploration has entered an exciting new era with private companies joining government agencies in the race to the stars. Recent technological breakthroughs have made space travel more accessible and economically viable than ever before. Reusable rocket technology, advanced satellite systems, and plans for lunar bases and Mars colonization are reshaping our understanding of what's possible. This commercial space age promises new opportunities for scientific research, resource exploitation, and even space tourism. However, it also raises important questions about space debris management, resource rights, and international cooperation in the final frontier.",
    "The human brain remains one of the most complex and fascinating organs in existence, with neuroscientists continuously uncovering new insights into its functioning. Recent research has revealed remarkable findings about neuroplasticity, memory formation, and consciousness. Studies show how our brains constantly rewire themselves in response to new experiences and learning, maintaining this adaptability throughout our lives. Understanding these mechanisms has led to breakthrough treatments for neurological conditions and innovative approaches to education and cognitive enhancement. The intersection of neuroscience with artificial intelligence is opening new frontiers in brain-computer interfaces and cognitive augmentation.",
    "The global food system is undergoing a dramatic transformation as we face the challenges of feeding a growing population while maintaining environmental sustainability. Innovative agricultural technologies, including vertical farming, precision agriculture, and lab-grown meat, are revolutionizing food production. These advances promise to reduce water usage, minimize land requirements, and decrease greenhouse gas emissions. Additionally, the rise of plant-based alternatives and cellular agriculture is reshaping consumer preferences and industry practices. However, ensuring equitable access to nutritious food while supporting small-scale farmers remains a critical challenge in this agricultural revolution.",
    "The digital revolution has fundamentally altered how we communicate, work, and interact with the world around us. Social media platforms have created global communities while simultaneously raising concerns about privacy, mental health, and the spread of misinformation. The rise of remote work, accelerated by recent global events, has transformed traditional office culture and labor markets. Blockchain technology and cryptocurrencies are challenging conventional financial systems, while the Internet of Things is creating increasingly connected and smart environments. As we navigate this digital transformation, questions of digital rights, cybersecurity, and technological inequality become increasingly important.",
];

export const Items = () => {
    const [currentPage, setCurrentPage] = useState(1);
    const newsPerPage = 6;

    const totalNews = randonTexts.length;
    const totalPages = Math.ceil(totalNews / newsPerPage);

    const indexOfLastPost = currentPage * newsPerPage;
    const indexOfFirstPost = indexOfLastPost - newsPerPage;
    const currentNews = randonTexts.slice(indexOfFirstPost, indexOfLastPost);

    const handlePageChange = page => {
        setCurrentPage(page);
        window.scrollTo({ top: 0, behavior: "smooth" });
    };

    return (
        <div className="flex flex-col md:gap-[40px] gap-[48px]">
            <div className="grid lg:grid-cols-3 md:grid-cols-2 grid-cols-1 md:gap-[24px] gap-[16px]">
                {currentNews.map((text, index) => (
                    <Item key={index} text={text} />
                ))}
            </div>
            <Pagination currentPage={currentPage} totalPages={totalPages} onPageChange={handlePageChange} />
        </div>
    );
};
